name: backend
description: Personal portfolio web app built with Dart Shelf and Flutter Web
version: 1.0.0+1
# MAJOR.MINOR.PATCH+BUILD_NUMBER
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3

dev_dependencies:
  lints: ^6.0.0
